repeatValuesAfter: 3600000
internalQueueSize: 10000
sensorConfig:
  nic: eth0
  sensorTypes:
    - POWER_METER
    - GAS_METER

mqttConfig:
  clientName: CS1F08_PM1
  url: tcp://localhost:1883
  userName: johndoe
  password: secret
  topics:
    - topic: p1/power
      type: POWER
    - topic: p1/gas
      type: GAS

serialPort:
  p1Key: /ISK5\2M550T-1013
  uart: /dev/ttyUSB0
  baudRate: 115200
