repeatValuesAfter: 3600000
internalQueueSize: 10000
nic: eth0
sensorConfigs:
  - type: POWER_PT1
    mqttTopic:  /power/pt1
  - type: POWER_PT2
    mqttTopic: /power/pt2
  - type: POWER_CT1
    mqttTopic: /power/ct1
  - type: POWER_CT2
    mqttTopic: /power/ct2
  - type: POWER_AC
    mqttTopic: /power/ac
  - type: POWER_AP
    mqttTopic: /power/ap
  - type: GAS_METER
    mqttTopic: /gas/c

mqttBroker:
  clientName: CS1F08_PM1
  url: tcp://localhost:1883
  userName: johndoe
  password: secret
  subscriptions:
    - p1
    - domiot

serialPort:
  p1Key: /ISK5\2M550T-1013
  uart: /dev/ttyUSB0
  baudRate: 115200
