
sensorConfig:
  nic: eth0
  sensorTypes: 
    - POWER_METER
    - GAS_METER
    
mqttConfig:
  clientName: CS1F08_PM1
  url: tcp://localhost:1883
  userName: johndoe
  password: secret
  topics: 
    - topic: lnb/eng/power
      type: POWER
    - topic: lnb/eng/gas
      type: GAS

serialPort:
  p1Key: /XMXunique_key
  uart: /dev/ttyUSB0
  baudRate: 115200
